doc: IFS-3646 add AsciiDoc
IsyFact/isy-angular-widgets pull request #198
Opened 2024-04-29 11:38 UTC by msg-jstren

2024-04-30 08:54 UTC, stdll commented on doc/antora-playbook.yml
Das Playbook und das ganze UI braucht ihr an der Stelle nicht. Es reicht, einen PR gegen das zentrale Playbook zu stellen und euch dort einzutragen: https://github.com/IsyFact/isyfact.github.io/blob/main/antora-playbook.yml

2024-04-30 09:02 UTC, stdll commented on doc/antora.yml
Aktuell enthalten die URLs zu eurer Dokumentation den Teil `.../isy-angular-widgets-doc/isy-angular-widgets/...`. Ihr könnt das auf `.../isy-angular-widgets/...` wiefolgt kürzen:
- `name`: isy-angular-widgets
- Es gibt ein implizites Modul mit dem Namen ROOT, das zu deutlich kürzeren URLs führt (Beispiel: https://github.com/IsyFact/isy-documentation/tree/master/documentation-guide). Ich empfehle euch, den Namen statt "isy-angular-widgets" zu nutzen. Dazu müsst ihr das Modulverzeichnis in "ROOT" umbenennen und `start_page` sowie `nav` anpassen.

2024-04-30 09:02 UTC, stdll commented on doc/antora.yml
> +display_version: '17.2.0'
In der restlichen Doku werden nur Minor-Releaes angegeben. Hier würde also `17.2` als Version genügen.

2024-04-30 12:03 UTC, msg-jstren commented on doc/antora.yml
name angepasst und Verzeichnis in ROOT umbenannt

2024-05-02 10:31 UTC, stdll approved these changes

2024-05-02 10:31 UTC, stdll commented on isy-angular-widgets-doc/modules/ROOT/pages/konzept/changelog.adoc
Das Asciidoc-Changelog wird bald abgelöst. Ihr könnt die Änderungen bereits jetzt schon in euer Projekt-Changelog aufnehmen.

2024-05-02 11:59 UTC, stdll approved these changes

2024-05-06 07:23 UTC, Aspern requested changes
In der Readme fehlt noch ein Link auf die Doku (Antora)

2024-05-06 07:23 UTC, Aspern commented on isy-angular-widgets-doc/modules/ROOT/pages/konzept/konzept.adoc
> +Umsetzung der User Interfaces in der gesamten Anwendungslandschaft zu gewährleisten.
```suggestion
In diesem Konzept werden die Anforderungen und Vorgaben der IsyFact, die im xref:isyfact-standards-doku:isy-bedienkonzept:bedienkonzept.adoc[Bedienkonzept und Styleguide] definiert sind, als Komponenten-Bibliothek umgesetzt oder in der dazugehörigen Demo-Anwendung exemplarisch dargestellt, um eine einheitliche Umsetzung der User Interfaces in der gesamten Anwendungslandschaft zu gewährleisten.
```

2024-05-06 07:23 UTC, Aspern commented on isy-angular-widgets-doc/modules/ROOT/pages/konzept/konzept.adoc
> +um die definierten Anforderungen zu erfüllen.
```suggestion
Dieses Dokument beschreibt alle Aspekte, die bei der Frontend-Entwicklung einer Anwendung zu berücksichtigen sind, um die definierten Anforderungen zu erfüllen.
```

2024-05-06 07:23 UTC, Aspern commented on isy-angular-widgets-doc/modules/ROOT/pages/konzept/konzept.adoc
> +in Kapitel <<anforderungen>> genannten Anforderungen in der zu diesem Baustein gehörenden Bibliothek.
```suggestion
Die folgenden architektonischen und technischen Vorgaben beziehen sich auf die Umsetzung der in Kapitel <<anforderungen>> genannten Anforderungen in der zu diesem Baustein gehörenden Bibliothek.
```

2024-05-06 09:21 UTC, merged